char *s = C_("GUI|Custom Partitioning|Confirm Delete Dialog", "_Cancel");
char *s = C_("GUI|Custom Partitioning|Confirm Delete Dialog", "_Delete It");
char *s = C_("GUI|Custom Partitioning|Configure Dialog", "_Cancel");
char *s = C_("GUI|Custom Partitioning|Configure Dialog", "_Select");
char *s = N_("CONFIGURE MOUNT POINT");
char *s = N_("Select one or more disks this device may reside on.");
char *s = N_("Description");
char *s = N_("Name");
char *s = N_("Capacity");
char *s = N_("Free");
char *s = C_("GUI|Custom Partitioning|Add Dialog", "_Cancel");
char *s = C_("GUI|Custom Partitioning|Add Dialog", "_Add mount point");
char *s = C_("GUI|Custom Partitioning|Add Dialog", "_Desired Capacity:");
char *s = C_("GUI|Custom Partitioning|Add Dialog", "Mount _Point:");
char *s = N_("ADD A NEW MOUNT POINT");
char *s = N_("More customization options are available\n"
             "after creating the mount point below.");
char *s = N_("That mount point is already in\n"
             "use.  Try something else?");
char *s = N_("eg: \"20 GB\", \"500mb\" (minus the quotation marks)");
char *s = N_("None");
char *s = N_("Single <span foreground=\"grey\">(No Redundancy, No Striping)</span>");
char *s = N_("RAID0 <span foreground=\"grey\">(Performance)</span>");
char *s = N_("RAID1 <span foreground=\"grey\">(Redundancy)</span>");
char *s = N_("RAID4 <span foreground=\"grey\">(Error Checking)</span>");
char *s = N_("RAID5 <span foreground=\"grey\">(Distributed Error Checking)</span>");
char *s = N_("RAID6 <span foreground=\"grey\">(Redundant Error Checking)</span>");
char *s = N_("RAID10 <span foreground=\"grey\">(Performance, Redundancy)</span>");
char *s = C_("GUI|Custom Partitioning|Container Dialog", "_Cancel");
char *s = C_("GUI|Custom Partitioning|Container Dialog", "_Save");
char *s = N_("CONFIGURE CONTAINER");
char *s = N_("Please create a name for this container and select at least one disk below.");
char *s = C_("GUI|Custom Partitioning|Container Dialog", "_Name:");
char *s = N_("RAID Level:");
char *s = N_("Encrypt");
char *s = N_("Please enter a valid name.");
char *s = C_("GUI|Custom Partitioning|Container Dialog", "Si_ze policy:");
char *s = N_("Automatic");
char *s = N_("As large as possible");
char *s = N_("Fixed");
