char *s = N_("Standard Partition");
char *s = N_("Btrfs");
char *s = N_("LVM");
char *s = N_("RAID");
char *s = N_("LVM Thin Provisioning");
char *s = N_("RAID0 <span foreground=\"grey\">(Performance)</span>");
char *s = N_("RAID1 <span foreground=\"grey\">(Redundancy)</span>");
char *s = N_("RAID4 <span foreground=\"grey\">(Error Checking)</span>");
char *s = N_("RAID5 <span foreground=\"grey\">(Distributed Error Checking)</span>");
char *s = N_("RAID6 <span foreground=\"grey\">(Redundant Error Checking)</span>");
char *s = N_("RAID10 <span foreground=\"grey\">(Performance, Redundancy)</span>");
char *s = N_("MANUAL PARTITIONING");
char *s = N_("Add a new mount point.");
char *s = C_("GUI|Custom Partitioning", "Add");
char *s = N_("Remove the selected mount point(s).");
char *s = C_("GUI|Custom Partitioning", "Remove");
char *s = N_("Reload storage configuration from disk.");
char *s = C_("GUI|Custom Partitioning", "Refresh");
char *s = N_("Selected Device");
char *s = N_("Device description");
char *s = N_("Mount _Point:");
char *s = N_("_Desired Capacity:");
char *s = N_("_Label:");
char *s = N_("Device(s):");
char *s = C_("GUI|Custom Partitioning|Configure|Devices", "_Modify...");
char *s = N_("_Name:");
char *s = C_("GUI|Custom Partitioning|Configure", "Device _Type:");
char *s = C_("GUI|Custom Partitioning|Configure", "_Encrypt");
char *s = C_("GUI|Custom Partitioning|Configure", "File S_ystem:");
char *s = C_("GUI|Custom Partitioning|Configure", "Ref_ormat");
char *s = C_("GUI|Custom Partitioning|Configure", "_Volume Group:");
char *s = C_("GUI|Custom Partitioning|Configure", "_Modify...");
char *s = C_("GUI|Custom Partitioning|Configure", "RA_ID Level:");
char *s = N_("_Update Settings");
char *s = N_("Note:  The settings you make on this screen will not be applied until you click on the main menu's 'Begin Installation' button.");
char *s = N_("This device is encrypted and cannot be read without a valid passphrase. You may unlock it below.");
char *s = C_("GUI|Custom Partitioning|Encrypted", "_Passphrase:");
char *s = C_("GUI|Custom Partitioning|Encrypted", "_Unlock");
char *s = N_("This device cannot be edited directly. You can remove it or select a different device.");
char *s = N_("AVAILABLE SPACE");
char *s = N_("TOTAL SPACE");
char *s = C_("GUI|Custom Partitioning", "_Reset All");
